# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(fname: "Bradley", lname: "Neal", email: "admin", password: "password", main_pic_url: "https://scontent.fsjc1-2.fna.fbcdn.net/hphotos-xfa1/t31.0-8/11539089_10152870304100738_943635186343598068_o.jpg", description: "I am a web developer based out of San Francisco, California. If you are looking for a sample of my work, take a look around this site! Originally from Washington, D.C., my hobbies include playing guitar, hiking, fly fishing and skiing.", birthday: "1991-10-14")
User.create!(fname: "Mike", lname: "Jordan", email: "mjordan", password: "password", main_pic_url: "https://blog-blogmediainc.netdna-ssl.com/upload/SportsBlogcom/2159727/0413747001456770288_filepicker.png", description: "After playing basketball professionally for over 10 years, I tried my hand at baseball and currently manage a 200 acre farm in the center of San Francisco, California. In my free time I enjoy chess and splicing rope.", birthday: "1963-2-17")
User.create!(fname: "Brittany", lname: "Howard", email: "bhoward", password: "password", main_pic_url: "http://static.jetmag.com/wp-content/uploads/2014/01/100091393-brittany-howard.jpg", description: "I am the lead singer of a band called Alabama Shakes. I have an amazing voice and my energy is true to the spirit of rock and roll. Before my band became popular, I was delivering mail for the US postal service. Life is crazy sometimes!", birthday: "1988-10-2")
User.create!(fname: "Louis", lname: "CK", email: "louisck", password: "password", main_pic_url: "http://media.salon.com/2012/11/louis_ck_slide.jpg", description: "Hey whats up I'm Louie CK. I never know what to say on these \'about me\' questionaires but Im a guy. I like food? If you are a fan of my work you should check out my new web series \'Horace and Pete\'. Cheers", birthday: "1967-9-12")
User.create!(fname: "Walter", lname: "Sobchak", email: "walter", password: "password", gender: "male", main_pic_url: "http://www.ew.com/sites/default/files/i/imgs/081117//John-Goodman-Lebowski_l.jpg", description: "You want a toe? I'll get you a toe by three o'clock this afternoon. With nailpolish. I run a security company called Sobchek Security. My interests include Charlie, Pomeranians and Bowling. Also, I'm shomer Shabbat.", birthday: "1945-6-20")
User.create!(fname: "Nora", lname: "Aron", email: "nora", password: "password", main_pic_url: "https://softbulletindotcom.files.wordpress.com/2012/07/img_0907.jpg", description: "Hello I am Nora.", birthday: "1994-5-23")

Yard.create!(title: "South", location: "Dolores Park", lng: -122.427406, lat: 37.760383, user_id: 5, description: "A little gem nestled between mountains with a river running through it, \'South\' reminds me of hill 53. We lost a lot of good men out there. If you want to stay on my property, feel free to send me a request. We have a lot of people trying to stay on this beautiful land. Do you see what happens, User, when you forgot to request a booking before hand?", transport_info: "Getting here can be a little bit tricky. I have access to a friend's car but you will have to wear goggles because the windshield is broken at the moment. There is a Ralph's closeby if you need supplies..")
Yard.create!(title: "West", location: "Golden Gate Park", lng: -122.487989, lat: 37.769556, user_id: 6, description: "Wide open plains and georeous mountains reminiscent of the Grand Tetons in the background, \'West\' is San Francisco's best kept secret. Don't forget to bring a saddle when you stop by, we have many horses and over 200 miles of public access trail for your riding pleasure. Giddy Up!", transport_info: "Getting to West from downtown San Francisco is a breeze. We are located on the other side of a utilities closet at App Academy in FIDI. Just enter the closet and keep walking. When you hear \'Howdy\' you've made it.")
Yard.create!(title: "North", location: "Hyde St. Pier", lng: -122.421307, lat: 37.809131, user_id: 4, description: "A beautiful plot of land. 300 Acres in downtown SF! \'North\' boasts a landscape reminiscent of the orient. With plenty of space available for camping and fishing, this is definitely a spot that you will not want to miss. Sunsets are spectacular.", transport_info: "Getting here is not too difficult, we are accessable by bart and muni with a short walk from the station to here. Private rides can be arranged but must be done with one week's notice.")
Yard.create!(title: "East", location: "App Academy", lng: -122.394049, lat: 37.791118, user_id: 3, description: "Don't forget a bring a water bottle when you come and visit this spectacular San Francisco bay ranch. The arid environment is similar to something you may expect to find in Colorado, Arizona or Utah, our red clay landscape will not disappoint. Please though, be aware that we do not allow open fires on our propery due to risk of forest fire caused by the dry nature of the surroundings.", transport_info: "Getting to East is pretty difficult. As we get many applications for potential bookings, we will notify you within one week if you have been selected. If so, we will send you a parachute and a map. From that point you will go to the location on the map and await our helicopter at the highest point at that longitude and latitude. There are no roads to or from East.")
Yard.create!(title: "Central", location: "Filmore Auditorium", lng: -122.433150, lat: 37.784145, user_id: 2, description: "A beautiful plot of land. 300 Acres in downtown SF! \'Central\' is similar in landscape and foliage to Utah's provo mountrain range. A world class fly-fishing destination for hobbiests and professionals alike, \'Central\' was ranked first in ESPN's top fly-fishing destinations of 2015", transport_info: "Getting to \'Central\' is very easy. We are located on Market between 3rd and 4th. Muni and Bart run all around.")
Yard.create!(title: "Babylon", location: "Other Side of the world", lng: 122.433150, lat: 37.784145, user_id: 1, description: "A beautiful plot of land. This property is perfect for those looking to get off the beaten path. Located somewhere around the south-china sea, this property was one of the first ever posted to YardSurfing and at the time was used for testing purposes to make sure the map's boundaries were accurately reflected in the search index." ,transport_info: "Getting here is not easy, you will need to make use of planes, trains, automobiles and at least one boat. Godspeed.")
Yard.create!(title: "Downtown", location: "Downtown", lng: -122.468147, lat: 37.746101, user_id: 1, description: "Downtown has been listed among the most peaceful locations posted on YardSurfing. Dispite the property's misleading name, Downtown is a santuary, perfect for quiet reflecion and meditation. A cool breeze, birds chirping and a quiet sunrise are things you can expect from Downtown. Come alone or with a friend!", transport_info: "To get to Downtown, simply take the downtown train downtown until you are no longer uptown.")
Yard.create!(title: "Bridge Bungalo", location: "Golden Gate", lng: -122.458167, lat: 37.746101, user_id: 6, description: "If you are familiar with the idea of a treehouse you will have no problem understanding what we do here at Bridge Bungalo. Imagine everything about a treehouse, but instead of being in a tree we are located in a cloud. The photo above was taken from our front porch. Think about a combination of the movie \'Up\' and the Jungle Book, somewhere in there.", transport_info: "Getting to \'Bridge Bungalo\' will not be easy. You must be hoiseted. It isnt pretty. For this reason we suggest being in average or better shape before booking a reservation.")
Yard.create!(title: "Picnic Perfect", location: "Dolores Park", lng: -122.478157, lat: 37.746101, user_id: 2, description: "A cave-like dwelling located within the side of a grassy knoll in San Francisco's historic Dolores Park, Picnic Perfect is one of YardSurfing's best kept secrets. Please remember to bring a flashlight should you choose to stay with us. We have the best seat in the house for all of Dolores Park's festivities!", transport_info: "Take the Bart or the Muni to Dolores Park. Upon arrival assume a head-stand position in the center of the park as a signal to us, from there we will take care of the rest.")
Yard.create!(title: "Ho Chi Minh", location: "Hideout Hostel", lng: 106.691892, lat: 10.768099, user_id: 6, description: "Unlike many of the other listings, Hideout Hostel is not a private park but rather a commercial Hostel located in Saigon, Vietnam. Hideout Hostel is a great place to meet people, have a drink and even potentially start a north-bound motorbike trip!", transport_info: "Getting to Hideout Hostel is not easy but is straightforward none the less. Grab a quick 17 flight to Ho Chi Minh city and snag a cab. See you soon!")
Yard.create!(title: "Phong Nha", location: "Easy Tiger Hostel", lng: 106.310667, lat: 17.610048, user_id: 6, description: "Phong Nha national Park is a true tresure. With unique beautiful topography and a not-yet-overrun tourism industry, Phong Nha is a great place to both see the wonders of Vietnam and also have a beer with fellow travellers. If you arrive by bus we recommend that you rent a motorbike and take a lap around the \'loop\' which someone at reception will be happy to map out for you. Phong Nha is also home to some of the world's biggest and most elaborate caves, including the world's biggest cave, Hang Son Doong.", transport_info: "Phong Nha is roughly located between Ho Chi Minh City and Hanoi, so either location would be appropriate for flying into. Once in Vietnam, take a bus or get a motorcycle and head towards the middle of the country!")
Yard.create!(title: "Tempelhof", location: "Berlin Park", lng: 13.391921, lat: 52.472142, user_id: 6, description: "Tempelhof is one of Berlin's best kept secrets. A favorite spot for locals named Nora, Templehof was once Berlin's major airport. After a vote in 2008 which came down against those who wanted to build apartment buildings on the land, Tempelhof was made into a park and is now a great place for picnics, bike rides, and concerts", transport_info: "Getting to Templehof is not super difficult assuming you are in Berlin. Just ask anyone!")

YardPhoto.create!(yard_id: 1, yard_pic_url: "http://i.imgur.com/aifkRiV.jpg")
YardPhoto.create!(yard_id: 2, yard_pic_url: "http://i.imgur.com/jAar9T5.jpg")
YardPhoto.create!(yard_id: 3, yard_pic_url: "http://i.imgur.com/DGb9XSW.jpg")
YardPhoto.create!(yard_id: 4, yard_pic_url: "http://i.imgur.com/duS6gz9.jpg")
YardPhoto.create!(yard_id: 5, yard_pic_url: "http://i.imgur.com/XuFVXyp.jpg")
YardPhoto.create!(yard_id: 6, yard_pic_url: "http://i.imgur.com/0fR0RmH.jpg")
YardPhoto.create!(yard_id: 7, yard_pic_url: "http://i.imgur.com/Q9wvEMu.jpg")
YardPhoto.create!(yard_id: 8, yard_pic_url: "http://i.imgur.com/uGzi76j.jpg")
YardPhoto.create!(yard_id: 9, yard_pic_url: "http://i.imgur.com/3lxbj7s.jpg")
YardPhoto.create!(yard_id: 10, yard_pic_url: "http://i.imgur.com/pdoQXI1.jpg")
YardPhoto.create!(yard_id: 11, yard_pic_url: "http://i.imgur.com/ovl1jup.jpg")
YardPhoto.create!(yard_id: 12, yard_pic_url: "http://i.imgur.com/axBjgNH.jpg")
